### ISSUE TITLE
Plugin reference old version of *Xamarin.GooglePlayServices.Base (= 32.961.0)*

### ISSUE THREAD

**Issue by IbrahimElshafey** [alexrainman/Analytics#1]
I can't use this plugin due to its reference `Xamarin.GooglePlayServices.Base (= 32.961.0)` that is old and other Xamarin NuGet package reference higher version.
`Xamarin.GooglePlayServices.Maps 60.1142.0 -> Xamarin.GooglePlayServices.Base (= 60.1142.0) 
 Plugin.Analytics 3.0.0 -> Xamarin.GooglePlayServices.Analytics 32.961.0 -> Xamarin.GooglePlayServices.Base (= 32.961.0)`

**Comment by IbrahimElshafey** [comment]
I downloaded the source code and upgrade Nuget packages, it works fine now.

**Comment by alexrainman** [comment]
I haven’t upgraded the plugin because google deprecated analytics for mobile apps 🤷🏻‍♂️

**Comment by IbrahimElshafey** [comment]
No, it still works fine. I created firebase application link it to analytics property and the plugin works fine, I searched in the web to find if mobile analytics is deprecated and I didn't find anything.
